version: '3'
services:
  localdb:
    image: mariadb:10.3.15
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
